services:
  - type: web
    name: xmsupport-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false
